### ISSUE TITLE
Balance without considering load

### ISSUE THREAD

**Issue by blanchma** [rjrodger/seneca-balance-client#20]
I was wondering if there is a plugin or feature that instead of just doing the distribution of request between services in order, it analyze the workload or delay of them.

For example:
base send to S1 and S2, one request for each every time. Instead, if S1 is delaying too much, it send two to S2 before sending again to S1.

**Comment by rjrodger** [comment]
check out https://github.com/dgonzalez/visigoth /cc @dgonzalez
