### ISSUE TITLE
parameterise the load-balancing algorithm 

### ISSUE THREAD

**Issue by rjrodger** [rjrodger/seneca-balance-client#3]
allow user to pass in a function as an option to control how this is done:

`seneca().use('balance-client', { strategy: function( ... ) { ... } } )`

At the moment, simplistic round-robin is hard-coded in:
https://github.com/rjrodger/seneca-balance-client/blob/master/balance-client.js#L156

**Comment by cjihrig** [comment]
Closing based on https://github.com/rjrodger/seneca-balance-client/issues/5#issuecomment-164571784
