### ISSUE TITLE
move repo to senecajs org

### ISSUE THREAD

**Issue by rjrodger** [rjrodger/seneca-balance-client#6]
once we are happy with quality
/cc @geek

**Comment by AdrieanKhisbe** [comment]
> touch this

**Comment by mcdonnelldean** [comment]
@rjrodger I think we are good to move this in. We are using it on a number of projects and I want to make sure the quality and visibility is where it needs to be.

**Comment by mcdonnelldean** [comment]
Closed as happening when the Golden Circle org changes happen.
