### ISSUE TITLE
pattern strings need to be canonical

### ISSUE THREAD

**Issue by rjrodger** [rjrodger/seneca-balance-client#9]
The representation of patterns as strings needs to be canonical as per https://github.com/senecajs/seneca/blob/master/seneca.js#L411
or we'll have fun and games with key mismatches

**Comment by cjihrig** [comment]
Is this done as of 999b0056bf45ba2dd95ec9abcf22fc1a72e46902?

**Comment by rjrodger** [comment]
yeah i think so - it was done in a rush and feels a bit hacky - you might want to review logic and see if it hangs together consistently

**Comment by rjrodger** [comment]
now using seneca.util.pincanon
